spring.config.import=classpath:private.properties

spring.application.name=backend

# PostgreSQL connection string
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=${DB_MODE}
spring.jpa.show-sql=true

# Spring Security
spring.security.user.name=${SECURITY_USERNAME}
spring.security.user.password=&{SECURITY_PASSWORD}