spring.config.import=classpath:db.properties

spring.application.name=backend

# PostgreSQL connection string
spring.datasource.url=${URL}
spring.datasource.username=${myUSERNAME}
spring.datasource.password=${myPASSWORD}

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=${MODE}
spring.jpa.show-sql=true